az login

# Create a service principal. (autogenerated)
az ad sp create --id

# Create using a self-signed certificate, and store it within KeyVault.
az ad sp create-for-rbac \
  -n 'if the anme does not exists, cli will gen one' \
  --keyvault 'MyVaultName' \
  --create-cert --cert 'CertName' \
  --skip-assignment true  # Allow accessing all resources
# --role Contributor  # default to Contributor 
# --scopes /subscriptions/{SubID}/resourceGroups/{ResourceGroup1} \
#          /subscriptions/{SubID}/resourceGroups/{ResourceGroup1}

az login \
  --service-principal \
  -u http://sample-cli-login \
  -p Test1234 \
  --tenant 54826b22-38d6-4fb2-bad9-b7b93a3e9c5a

az account list

az account list --query [?isDefault]  # Current default subscription
az account set 'subscription name or id'

az account clear  # Removing all access credentials


